primaryColor=#39302b
secondaryColor=#236595
labelColor=#ffffff
hideWhenOffline=false
contactMail=admin@support.com
loadingLabel=Loading...
loginError=Can't login
chatHeader=Live Support PTPN-II
startInfo=Silahkan isi data Anda untuk memulai percakapan.
startLabel=Mulai
backLabel=Kembali
initMessageBody=Hallo, Ada yang bisa kami bantu :)
initMessageAuthor=Live Support PTPN-II
chatInputLabel=Ketik Disini
timeDaysAgo=day(s) ago
timeHoursAgo=hour(s) ago
timeMinutesAgo=minute(s) ago
timeSecondsAgo=second(s) ago
offlineMessage=Operator Sedang Offline
toggleSoundLabel=Sound effects
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
contactHeader=Live Support PTPN-II
contactInfo=Maaf, semua operator Kami sedang Offline. Silahkan kirim keluhan Anda disini.
contactNameLabel=Nama Anda
contactMailLabel=Email Anda
contactQuestionLabel=Keluhan Anda
contactSendLabel=Kirim
contactSuccessHeader=Pesan Terkirim
contactSuccessMessage=Terima Kasih, pesan Anda telah Kami Terima.
contactErrorHeader=Error
contactErrorMessage=There was an error sending your question
maxConnections=5
messageSound=audio/tingtung.mp3
installed=1
